export const RESOURCES = [
  {
    id: "freecodecamp",
    title: "freeCodeCamp",
    url: "https://www.freecodecamp.org/",
    description:
      "Hands-on coding challenges, full certifications, and projects.",
    category: "General",
    emoji: "🎓",
    tags: ["HTML", "CSS", "JS", "APIs", "Certifications"],
  },
  {
    id: "coursera",
    title: "Coursera",
    url: "https://www.coursera.org/",
    description: "University-level courses across tech and beyond.",
    category: "General",
    emoji: "🎒",
    tags: ["Computer Science", "Cloud", "ML/AI"],
  },
  {
    id: "w3schools",
    title: "W3Schools",
    url: "https://www.w3schools.com/",
    description: "Quick references and tutorials for web tech.",
    category: "Frontend",
    emoji: "📗",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    id: "node-docs",
    title: "Node.js Docs",
    url: "https://nodejs.org/en/docs",
    description: "Official Node.js runtime documentation.",
    category: "Backend",
    emoji: "🟩",
    tags: ["Node", "Runtime", "API"],
  },
  {
    id: "express-docs",
    title: "Express Docs",
    url: "https://expressjs.com/",
    description: "Fast, unopinionated, minimalist web framework for Node.js.",
    category: "Backend",
    emoji: "🚂",
    tags: ["Node", "HTTP", "Middleware"],
  },
  {
    id: "ts-handbook",
    title: "TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    description: "Official TS docs & handbook to level up your type safety.",
    category: "Frontend",
    emoji: "🟦",
    tags: ["TypeScript", "Types", "Tooling"],
  },
  {
    id: "statquest",
    title: "StatQuest (Josh Starmer)",
    url: "https://www.youtube.com/c/joshstarmer",
    description: "Crystal clear stats & ML explanations.",
    category: "Data",
    emoji: "📊",
    tags: ["Statistics", "ML", "Data Science"],
  },
  {
    id: "aws-youtube",
    title: "AWS YouTube",
    url: "https://www.youtube.com/user/amazonwebservices",
    description: "Official AWS channel: services, tutorials, and events.",
    category: "Cloud",
    emoji: "☁️",
    tags: ["AWS", "Cloud", "DevOps"],
  },
];

export const CATEGORIES = [
  "All",
  "Frontend",
  "Backend",
  "Data",
  "Cloud",
  "General",
];
